version: '2'

services:
  mysql:
    build: ./docker/mysql
    ports:
      - "3312:3306"
    volumes:
      - "./volumes/mysql:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    command:
      - '--default-authentication-plugin=mysql_native_password'
      - '--character-set-server=utf8mb4'

  php-fpm:
    build: ./docker/php
    links:
      - mysql
    volumes:
      - "./app:/app"
    environment:
      DB_HOST: mysql

  nginx:
    build: ./docker/nginx
    volumes:
      - "./app:/app"
      - "./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
    links:
      - php-fpm
    ports:
      - "8010:80"

  redis:
    image: redis:latest
    volumes:
      - "/.redis:/data"
    ports:
        - '6379:6379'
  cron:
    build: ./docker/php
    restart: always
    command: bash -c "echo '* * * * * root cd /app && php artisan schedule:run >> /dev/null 2>&1' >> /etc/crontab && chmod +x /app/cron.sh && /app/cron.sh"
    links:
      - mysql
    volumes:
      - "./app:/app"
    environment:
      DB_HOST: mysql

  laravel-worker:
     build: ./docker/php
     links:
       - mysql
     volumes:
       - "./app:/app"
     environment:
       DB_HOST: mysql
     command: "php artisan queue:work --daemon"